//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Insight.MTP.Client.Common.Entity
{
    public partial class ImageData
    {
        public Guid ID { get; set; }
        public long SN { get; set; }
        public Guid? CategoryId { get; set; }
        public int ImageType { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Expand { get; set; }
        public Guid? SecrecyDegree { get; set; }
        public int? Pages { get; set; }
        public long? Size { get; set; }
        public string Path { get; set; }
        public byte[] Image { get; set; }
        public string Description { get; set; }
        public bool Validity { get; set; }
        public Guid? CreatorDeptId { get; set; }
        public Guid CreatorUserId { get; set; }
        public DateTime CreateTime { get; set; }
    }
}
